name=wmbus-drivers
version=1.0.0
author=jpaszkowski
maintainer=jpaszkowski
sentence=Header-only wM-Bus meter drivers
paragraph=
category=Communication
url=https://github.com/jpaszkowski/wmbus-drivers
architectures=*
includes=drivers.h
